language: node_js

matrix:
  include:
      - node_js: node
        os: linux
      - node_js: node
        os: osx
      - node_js: 11
        os: linux
      - node_js: 11
        os: osx
      - node_js: 10
        os: linux
      - node_js: 10
        os: osx
      - node_js: 8
        os: linux
      - node_js: 8
        os: osx
      - node_js: 8
        os: linux
      - node_js: 8
        os: osx
      - node_js: 7
        os: linux
      - node_js: 7
        os: osx
      - node_js: 6
        os: linux
      - node_js: 6
        os: osx

cache:
  directories:
    - node_modules

script:
  - npm run build
